# Generated by Django 6.1.2 on 2026-10-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('ticket_date', models.DateField()),
                ('ticket_type', models.IntegerField()),
                ('ticket_number', models.CharField(verbose_name=255)),
            ],
        ),
    ]
