# Generated by Django 6.1.2 on 2026-10-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ticket_type',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'VIP'), (3, 'Premium')]),
        ),
    ]
